# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Pull Request
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0
      - name: Go Mod
        run: go mod vendor
      - name: Go Build
        run: go build -v --mod=vendor -ldflags "-X github.com/openshift-splat-team/mapi-static-ip-controller/pkg/version.Raw=${{ vars.GITHUB_REF_NAME }} -X github.com/openshift-splat-team/mapi-static-ip-controller/pkg/version.Commit=${{ vars.GITHUB_SHA }}"  -o "bin/mapi-static-ip-controller" ./cmd/mapi-static-ip-controller

